Algoritmo "PetPlace"
// COMPRA POR QUILO
// DESCONTO
// QUANTIDADE DE UNIDADES

Var
opcao : caractere

Inicio
escreval("********catalogo*********")
escreval("1 - RACAO PREMIER KG       R$ 36,00")
escreval("2 - COLEIRA PEITORAL 2M    R$ 27,49")
escreval("3 - CASA DE TRANSPORTE     R$ 120,35")
escreval("4 - PETISCOS DOGPET 300G   R$ 12,00")
escreval("5 - TAPETE HIGIENICO       R$ 45,00")
escreval("6 - CANCELAR")
escreval("7 - CARRINHO")

leia(opcao)

Fimalgoritmo