Algoritmo "recepcao"

Var
nome, email : caractere
idade : inteiro

Inicio
escreval("Boa Tarde! Digite seu nome: ")
leia(nome)
limpaTela()

escreval("Digite a sua idade: ")
leia(idade)
limpaTela()

escreval("Digite seu email: ")
leia(email)
limpaTela()

escreval("Cadastro Efetuado com Sucesso!")
escreval("**************")
escreval("Usuario : ",nome)
escreval("Idade : ",idade)
escreval("Email : ",email)
escreval("**************")

Fimalgoritmo