Algoritmo "SomaDeQuatroNumeros"

Var
    num1, num2, num3, num4: inteiro
    soma: inteiro

Inicio
    escreva("Digite o primeiro número: ")
    leia(num1)

    escreva("Digite o segundo número: ")
    leia(num2)

    escreva("Digite o terceiro número: ")
    leia(num3)

    escreva("Digite o quarto número: ")
    leia(num4)

    soma <- num1 + num2 + num3 + num4

    escreva("A soma total dos números é: ", soma)
Fimalgoritmo